services:
  web_api:
    container_name: api
    build: .
    ports:
      - 8080:8080
      - 5264:5264
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "db"
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: Lar@123
      POSTGRES_DB: lardb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
